spring:
  application:
    name: sku-aggregator-service
services:
  catalog:
    base-url: https://catalog-master-service-prod.prod.internal.sephora.com/catalog-master-service/v1
  pxs:
    base-url: https://pxs.example.com
  skuhold:
    base-url: https://skuhold.example.com
